name: vncitizens_home
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vncitizens_common:
    git:
      url: https://scm.devops.vnpt.vn/egov.ptpm.g038/flutter_vncitizens
      ref: v1.0.0
      path: packages/vncitizens_common
  vncitizens_petition:
    git:
      url: https://scm.devops.vnpt.vn/egov.ptpm.g038/flutter_vncitizens
      ref: v1.0.0
      path: packages/vncitizens_petition
  vncitizens_account:
    git:
      url: https://scm.devops.vnpt.vn/egov.ptpm.g038/flutter_vncitizens
      ref: v1.0.0
      path: packages/vncitizens_account
  vncitizens_setting:
    git:
      url: https://scm.devops.vnpt.vn/egov.ptpm.g038/flutter_vncitizens
      ref: v1.0.0
      path: packages/vncitizens_setting
  vncitizens_payment:
    git:
      url: https://scm.devops.vnpt.vn/egov.ptpm.g038/flutter_vncitizens
      ref: v1.0.0
      path: packages/vncitizens_payment

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  assets:
    - packages/vncitizens_home/assets/images/banners/covid_19_1.png
    # menu
    - packages/vncitizens_home/assets/images/menu/cong_thong_tin.png
    - packages/vncitizens_home/assets/images/menu/danh_ba_khan_cap.png
    - packages/vncitizens_home/assets/images/menu/dich_vu_cong.png
    - packages/vncitizens_home/assets/images/menu/bat_so_xep_hang.png
    - packages/vncitizens_home/assets/images/menu/phan_anh_kien_nghi.png
    - packages/vncitizens_home/assets/images/menu/tim_kiem_dia_diem.png
    - packages/vncitizens_home/assets/images/menu/camera.png
    - packages/vncitizens_home/assets/images/menu/moi_truong.png
    - packages/vncitizens_home/assets/images/menu/van_ban_nha_nuoc.png
    - packages/vncitizens_home/assets/images/menu/goi_phan_anh.png
    - packages/vncitizens_home/assets/images/menu/thanh_toan.png
    - packages/vncitizens_home/assets/images/menu/phong_chong_dich_benh.png
    - packages/vncitizens_home/assets/images/menu/chat_tu_van_covid.png
    - packages/vncitizens_home/assets/images/menu/thong_tin_can_biet.png
    - packages/vncitizens_home/assets/images/menu/an_sinh_xa_hoi.png
    - packages/vncitizens_home/assets/images/menu/kinh_te.png
    - packages/vncitizens_home/assets/images/menu/du_lich.png
    - packages/vncitizens_home/assets/images/menu/dat_dai.png
    - packages/vncitizens_home/assets/images/menu/garbage_truck.png
    - packages/vncitizens_home/assets/images/menu/momo.png
    - packages/vncitizens_home/assets/images/menu/rating.png
    - packages/vncitizens_home/assets/images/menu/viettel_pay.png
    - packages/vncitizens_home/assets/images/menu/vnpt_pay.png
    # VNPT PAY SERVICES
    - packages/vncitizens_home/assets/images/menu/vnpt_pay_electronic.png
    - packages/vncitizens_home/assets/images/menu/vnpt_pay_water.png
    - packages/vncitizens_home/assets/images/menu/vnpt_pay_vntt.png
    - packages/vncitizens_home/assets/images/menu/vnpt_pay_htvc.png
    - packages/vncitizens_home/assets/images/menu/vnpt_pay_kplus.png
    - packages/vncitizens_home/assets/images/menu/vnpt_pay_cast_into_wallet.png
    - packages/vncitizens_home/assets/images/menu/vnpt_pay_vnedu.png
    - packages/vncitizens_home/assets/images/menu/vnpt_pay_vtvcab.png
    - packages/vncitizens_home/assets/images/menu/vnpt_pay_mytvnet.png
    - packages/vncitizens_home/assets/images/menu/vnpt_pay_telecom.png
    - packages/vncitizens_home/assets/images/menu/vnpt_pay_telecomv2.png
    - packages/vncitizens_home/assets/images/menu/vnpt_pay_internet.png
    - packages/vncitizens_home/assets/images/menu/vnpt_pay_static_phone.png
    - packages/vncitizens_home/assets/images/menu/vnpt_pay_vina_id.png
    - packages/vncitizens_home/assets/images/menu/vnpt_pay_transfer_into_wallet.png
    - packages/vncitizens_home/assets/images/menu/vnpt_pay_telecom_data.png
    - packages/vncitizens_home/assets/images/menu/vnpt_pay_fee.png
    # others
    - packages/vncitizens_home/assets/images/others/cloudy.png
    - packages/vncitizens_home/assets/images/others/update_image.png

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
