#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)
#ifndef BIOSDK_SWIFT_H
#define BIOSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BioSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSString;
@class NSNumber;
@class UIView;
@class UIColor;
enum PostionCamera : NSInteger;
@class FaceStep;
enum Language : NSInteger;

SWIFT_CLASS("_TtC6BioSDK13AdvanceOption")
@interface AdvanceOption : NSObject
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull help;
@property (nonatomic, copy) NSString * _Nonnull titleButtonRetake;
@property (nonatomic, copy) NSString * _Nonnull titleButtonNext;
@property (nonatomic) BOOL isShowTutorial;
@property (nonatomic, copy) NSString * _Nonnull logoNameImage;
@property (nonatomic) BOOL isShowLogo;
@property (nonatomic, copy) NSString * _Nonnull titleBtnHelp;
@property (nonatomic, strong) UIView * _Nullable contentPreviewView;
@property (nonatomic, strong) UIView * _Nullable tutorialView;
@property (nonatomic, copy) NSString * _Nonnull titleBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nonnull textColorBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nullable textColorBtnRetake;
@property (nonatomic, strong) UIColor * _Nullable textColorBtnNext;
@property (nonatomic, strong) UIColor * _Nullable bgColorBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nullable bgColor;
@property (nonatomic, strong) UIColor * _Nullable bgBtnRetakeColor;
@property (nonatomic, strong) UIColor * _Nullable bgNextColor;
@property (nonatomic) enum PostionCamera postionCamera;
@property (nonatomic, strong) UIColor * _Nullable progressBarColor;
@property (nonatomic, copy) NSString * _Nonnull imageTopLine;
@property (nonatomic, copy) NSString * _Nonnull imageSquareBottom;
@property (nonatomic, strong) UIColor * _Nullable colorStepNext;
@property (nonatomic) BOOL isShowArrowStep;
@property (nonatomic) BOOL isShowWaveGuilde;
@property (nonatomic) BOOL isAutoNext;
@property (nonatomic) NSInteger countdownTime;
@property (nonatomic, strong) UIColor * _Nullable titleColor;
@property (nonatomic, copy) NSString * _Nonnull iconBack;
@property (nonatomic, strong) UIColor * _Nullable textContentColor;
@property (nonatomic, strong) UIColor * _Nullable backgroundHelpButton;
@property (nonatomic, strong) UIColor * _Nullable textHelpButtonColor;
@property (nonatomic) BOOL isAnimatedDismiss;
@property (nonatomic) BOOL isShowPreviewTitle;
@property (nonatomic) BOOL isTakeMoreImage;
@property (nonatomic) BOOL isShowVersion;
@property (nonatomic, copy) NSDictionary<NSAttributedStringKey, id> * _Nullable titleAttributes;
@property (nonatomic, copy) NSDictionary<NSAttributedStringKey, id> * _Nullable titleButtonRetakeAttributes;
@property (nonatomic, copy) NSDictionary<NSAttributedStringKey, id> * _Nullable titleButtonNextAttributes;
@property (nonatomic, copy) NSDictionary<NSAttributedStringKey, id> * _Nullable titleBtnHelpAttributes;
@property (nonatomic, copy) NSDictionary<NSAttributedStringKey, id> * _Nullable titleBtnUnderstandAttributes;
@property (nonatomic, copy) NSDictionary<NSAttributedStringKey, id> * _Nullable textStepFaceAttributes;
@property (nonatomic, copy) NSArray<FaceStep *> * _Nonnull faceSteps;
@property (nonatomic) BOOL isVibrate;
@property (nonatomic) BOOL isMirrorFrontCamera;
@property (nonatomic) BOOL isStreamCapture;
@property (nonatomic) BOOL isRecord;
@property (nonatomic) NSInteger maxTimeRecord;
@property (nonatomic) enum Language tutorialLanguage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6BioSDK11BasicOption")
@interface BasicOption : NSObject
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull help;
@property (nonatomic, copy) NSString * _Nonnull titleButtonRetake;
@property (nonatomic, copy) NSString * _Nonnull titleButtonNext;
@property (nonatomic, copy) NSString * _Nonnull titleBtnHelp;
@property (nonatomic, copy) NSString * _Nonnull textContentPreview;
@property (nonatomic, strong) UIView * _Nullable tutorialView;
@property (nonatomic) BOOL isShowTutorial;
@property (nonatomic, copy) NSString * _Nonnull logoNameImage;
@property (nonatomic) BOOL isShowLogo;
@property (nonatomic, copy) NSString * _Nonnull titleBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nonnull textColorBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nullable textColorBtnRetake;
@property (nonatomic, strong) UIColor * _Nullable textColorBtnNext;
@property (nonatomic, strong) UIColor * _Nullable bgColorBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nullable bgColor;
@property (nonatomic, strong) UIColor * _Nullable bgBtnRetakeColor;
@property (nonatomic, strong) UIColor * _Nullable bgNextColor;
@property (nonatomic) enum PostionCamera postionCamera;
@property (nonatomic) BOOL isSwapCamera;
@property (nonatomic, copy) NSString * _Nonnull imageTopLine;
@property (nonatomic, copy) NSString * _Nonnull imageSquareBottom;
@property (nonatomic, strong) UIColor * _Nullable imageCircleColor;
@property (nonatomic) BOOL isAutoNext;
@property (nonatomic) NSInteger countdownTime;
@property (nonatomic, strong) UIColor * _Nullable titleColor;
@property (nonatomic, copy) NSString * _Nonnull iconBack;
@property (nonatomic, copy) NSString * _Nonnull iconSwapCamera;
@property (nonatomic, copy) NSString * _Nonnull iconTakePhoto;
@property (nonatomic, strong) UIColor * _Nullable textContentColor;
@property (nonatomic, strong) UIColor * _Nullable backgroundHelpButton;
@property (nonatomic, strong) UIColor * _Nullable textHelpButtonColor;
@property (nonatomic, strong) UIColor * _Nullable textContentPreviewColor;
@property (nonatomic) BOOL isAnimatedDismiss;
@property (nonatomic) BOOL isShowPreviewTitle;
@property (nonatomic) BOOL isShowVersion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@protocol CameraDelegate;
enum DocumentType : NSInteger;
@class OneSideOption;
@class TwoSideOption;
@class OvalOption;
@class UIViewController;

SWIFT_CLASS("_TtC6BioSDK6Camera")
@interface Camera : NSObject
@property (nonatomic, strong) id <CameraDelegate> _Nullable delegate;
@property (nonatomic) enum DocumentType documentType;
@property (nonatomic, strong) OneSideOption * _Nullable oneSideOption;
@property (nonatomic, strong) TwoSideOption * _Nullable twoSideOption;
@property (nonatomic, strong) BasicOption * _Nullable basicOption;
@property (nonatomic) enum Language language;
@property (nonatomic, strong) AdvanceOption * _Nonnull advanceOption;
@property (nonatomic, strong) OvalOption * _Nonnull ovalOption;
- (void)show:(UIViewController * _Nonnull)controller;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class DataModel;
@class UIImage;
enum FaceStepType : NSInteger;
@class ImageData;

SWIFT_PROTOCOL("_TtP6BioSDK14CameraDelegate_")
@protocol CameraDelegate
- (void)onResult:(DataModel * _Nonnull)data;
@optional
- (void)onStreamCapture:(UIImage * _Nonnull)image :(enum FaceStepType)type;
- (void)onStreamCaptureImageData:(ImageData * _Nonnull)image :(enum FaceStepType)type;
@required
- (void)onClose;
@optional
- (void)onError:(NSString * _Nonnull)message;
@end

@class NSURL;
@class NSData;

SWIFT_CLASS("_TtC6BioSDK9DataModel")
@interface DataModel : NSObject
@property (nonatomic, strong) UIImage * _Nullable image;
@property (nonatomic, strong) UIImage * _Nullable frontImage;
@property (nonatomic, strong) UIImage * _Nullable backImage;
@property (nonatomic, strong) UIImage * _Nullable farImage;
@property (nonatomic, strong) UIImage * _Nullable nearImage;
@property (nonatomic, strong) ImageData * _Nullable imageData;
@property (nonatomic, strong) ImageData * _Nullable frontImageData;
@property (nonatomic, strong) ImageData * _Nullable backImageData;
@property (nonatomic, strong) ImageData * _Nullable farImageData;
@property (nonatomic, strong) ImageData * _Nullable nearImageData;
@property (nonatomic) enum DocumentType documentType;
@property (nonatomic, copy) NSArray<UIImage *> * _Nonnull listPhoto;
@property (nonatomic, copy) NSArray<ImageData *> * _Nonnull listPhotoImageData;
@property (nonatomic) float topCropParam;
@property (nonatomic) float bottomCropParam;
@property (nonatomic, copy) NSArray<UIImage *> * _Nonnull listFaceSteps;
@property (nonatomic, copy) NSArray<ImageData *> * _Nonnull listFaceStepsImageData;
@property (nonatomic, copy) NSURL * _Nullable scanUrl;
@property (nonatomic, copy) NSData * _Nullable logData;
- (NSString * _Nonnull)getCropParam SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nonnull)cropImageWithImage:(UIImage * _Nonnull)image SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, DocumentType, open) {
  DocumentTypeOneside = 0,
  DocumentTypeTwoside = 1,
  DocumentTypeBasic = 3,
  DocumentTypeAdvanced = 4,
  DocumentTypeOval = 5,
};


SWIFT_CLASS("_TtC6BioSDK8FaceStep")
@interface FaceStep : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) enum FaceStepType type;
@property (nonatomic, strong) UIView * _Nullable viewGuide;
@property (nonatomic, copy) NSString * _Nonnull textGuide;
@property (nonatomic, copy) NSString * _Nonnull jsonArrowGuide;
@property (nonatomic, copy) NSString * _Nonnull jsonWaveGuide;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable dataJsonArrowGuide;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable dataJsonWaveGuide;
@end

typedef SWIFT_ENUM(NSInteger, FaceStepType, open) {
  FaceStepTypeLeft = 0,
  FaceStepTypeRight = 1,
  FaceStepTypeUp = 2,
  FaceStepTypeDown = 3,
  FaceStepTypeStraight = 4,
};


SWIFT_CLASS("_TtC6BioSDK9ImageData")
@interface ImageData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6BioSDK20InvalidDocumentAlert")
@interface InvalidDocumentAlert : NSObject
@property (nonatomic, copy) NSString * _Nonnull mesage;
@property (nonatomic, copy) NSString * _Nonnull buttonText;
@property (nonatomic, strong) UIColor * _Nullable messageColor;
@property (nonatomic, strong) UIColor * _Nullable buttonTextColor;
@property (nonatomic, strong) UIColor * _Nullable buttonColor;
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, Language, open) {
  LanguageVn = 0,
  LanguageEn = 1,
};

typedef SWIFT_ENUM(NSInteger, LivenessMode, open) {
  LivenessModeOnline = 0,
  LivenessModeOffline = 1,
};



SWIFT_CLASS("_TtC6BioSDK13OneSideOption")
@interface OneSideOption : NSObject
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull help;
@property (nonatomic, copy) NSString * _Nonnull titleButtonRetake;
@property (nonatomic, copy) NSString * _Nonnull titleButtonNext;
@property (nonatomic, copy) NSString * _Nonnull btnFinishTitle;
@property (nonatomic, copy) NSString * _Nonnull titleBtnHelp;
@property (nonatomic, copy) NSString * _Nonnull textContentPreview;
@property (nonatomic) BOOL isShowTutorial;
@property (nonatomic, copy) NSString * _Nonnull logoNameImage;
@property (nonatomic) BOOL isShowLogo;
@property (nonatomic, copy) NSString * _Nonnull titleBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nonnull textColorBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nullable textColorBtnRetake;
@property (nonatomic, strong) UIColor * _Nullable textColorBtnNext;
@property (nonatomic, strong) UIColor * _Nullable bgColorBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nullable bgColorPreview;
@property (nonatomic, strong) UIColor * _Nullable bgBtnRetakeColor;
@property (nonatomic, strong) UIColor * _Nullable bgNextColor;
@property (nonatomic, strong) UIView * _Nullable tutorialView;
@property (nonatomic) BOOL isAutoNext;
@property (nonatomic) NSInteger countdownTime;
@property (nonatomic, strong) UIColor * _Nullable titleColor;
@property (nonatomic, copy) NSString * _Nonnull iconBack;
@property (nonatomic, copy) NSString * _Nonnull textGuideImage;
@property (nonatomic, strong) UIColor * _Nullable backgroundHelpButton;
@property (nonatomic, strong) UIColor * _Nullable textHelpButtonColor;
@property (nonatomic, copy) NSString * _Nonnull iconTakePhoto;
@property (nonatomic, strong) UIColor * _Nullable textContentColor;
@property (nonatomic, strong) UIColor * _Nullable textContentPreviewColor;
@property (nonatomic, copy) NSString * _Nonnull jsonAnimationPreview;
@property (nonatomic, copy) NSString * _Nonnull imgBackgroundPreview;
@property (nonatomic, copy) NSString * _Nonnull imageTopViewCamera;
@property (nonatomic, copy) NSString * _Nonnull imageBottomViewCamera;
@property (nonatomic, copy) NSString * _Nonnull imageMarkFrameCamera;
@property (nonatomic, strong) UIColor * _Nullable textGuideImageColor;
@property (nonatomic) BOOL isAnimatedDismiss;
@property (nonatomic) BOOL isShowPreviewTitle;
@property (nonatomic) BOOL isShowVersion;
@property (nonatomic) BOOL isPreviewAnimation;
@property (nonatomic, strong) UIColor * _Nullable frameCornerColor;
@property (nonatomic, strong) UIColor * _Nullable backgroundCameraColor;
@property (nonatomic) BOOL isValidDocument;
@property (nonatomic, strong) InvalidDocumentAlert * _Nonnull invalidDocumentAlert;
@property (nonatomic, copy) NSString * _Nonnull textDescriptionInvalid;
@property (nonatomic, strong) UIColor * _Nullable doneButtonBackgroundDisableColor;
@property (nonatomic, strong) UIColor * _Nullable textDescriptionInvalidColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6BioSDK10OvalOption")
@interface OvalOption : NSObject
@property (nonatomic) BOOL isShowTutorial;
@property (nonatomic) BOOL isSkipTutorial;
@property (nonatomic) enum Language language;
@property (nonatomic, strong) UIView * _Nullable tutorialView;
@property (nonatomic, strong) UIImage * _Nullable bottomImage;
@property (nonatomic, strong) UIColor * _Nullable ovalCircleColor;
@property (nonatomic, strong) UIColor * _Nullable buttonTextColor;
@property (nonatomic, strong) UIColor * _Nullable textFeedbackColor;
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
@property (nonatomic, strong) UIColor * _Nullable bgColorBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nonnull textColorBtnUnderstand;
@property (nonatomic, copy) NSString * _Nonnull titleBtnUnderstand;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, PostionCamera, open) {
  PostionCameraBack = 0,
  PostionCameraFront = 1,
};

typedef SWIFT_ENUM(NSInteger, TutorialType, open) {
  TutorialTypeId = 0,
  TutorialTypeIdcard = 1,
  TutorialTypePassport = 2,
  TutorialTypeMilitary = 3,
  TutorialTypeBasic = 4,
  TutorialTypeAdvanced = 5,
};


SWIFT_CLASS("_TtC6BioSDK13TwoSideOption")
@interface TwoSideOption : NSObject
@property (nonatomic, copy) NSString * _Nonnull titleFont;
@property (nonatomic, copy) NSString * _Nonnull titleBack;
@property (nonatomic, copy) NSString * _Nonnull frontHelpPreview;
@property (nonatomic, copy) NSString * _Nonnull backHelpPreview;
@property (nonatomic, copy) NSString * _Nonnull frontHelp;
@property (nonatomic, copy) NSString * _Nonnull backHelp;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic) BOOL isShowTutorial;
@property (nonatomic, copy) NSString * _Nonnull logoNameImage;
@property (nonatomic) BOOL isShowLogo;
@property (nonatomic, copy) NSString * _Nonnull titleButtonRetake;
@property (nonatomic, copy) NSString * _Nonnull titleButtonNext;
@property (nonatomic, copy) NSString * _Nonnull btnFinishTitle;
@property (nonatomic, copy) NSString * _Nonnull titleBtnHelp;
@property (nonatomic, strong) UIView * _Nullable tutorialView;
@property (nonatomic, copy) NSString * _Nonnull titleBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nonnull textColorBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nullable textColorBtnRetake;
@property (nonatomic, strong) UIColor * _Nullable textColorBtnNext;
@property (nonatomic, strong) UIColor * _Nullable bgColorBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nullable bgColorPreview;
@property (nonatomic, strong) UIColor * _Nullable bgBtnRetakeColor;
@property (nonatomic, strong) UIColor * _Nullable bgNextColor;
@property (nonatomic) BOOL isAutoNext;
@property (nonatomic) NSInteger countdownTime;
@property (nonatomic, strong) UIColor * _Nullable titleColor;
@property (nonatomic, copy) NSString * _Nonnull iconBack;
@property (nonatomic, strong) UIColor * _Nullable backgroundHelpButton;
@property (nonatomic, strong) UIColor * _Nullable textHelpButtonColor;
@property (nonatomic, copy) NSString * _Nonnull iconTakePhoto;
@property (nonatomic, strong) UIColor * _Nullable textContentColor;
@property (nonatomic, strong) UIColor * _Nullable textContentPreviewColor;
@property (nonatomic, copy) NSString * _Nonnull jsonAnimationPreview;
@property (nonatomic, copy) NSString * _Nonnull imgBackgroundPreview;
@property (nonatomic, copy) NSString * _Nonnull imageTopViewCamera;
@property (nonatomic, copy) NSString * _Nonnull imageBottomViewCamera;
@property (nonatomic, copy) NSString * _Nonnull imageMarkFrameCamera;
@property (nonatomic, strong) UIColor * _Nullable textGuideImageColor;
@property (nonatomic) BOOL isAnimatedDismiss;
@property (nonatomic) BOOL isShowPreviewTitle;
@property (nonatomic) BOOL isShowVersion;
@property (nonatomic) BOOL isPreviewAnimation;
@property (nonatomic, strong) UIColor * _Nullable frameCornerColor;
@property (nonatomic, strong) UIColor * _Nullable backgroundCameraColor;
@property (nonatomic) BOOL isValidDocument;
@property (nonatomic, strong) InvalidDocumentAlert * _Nonnull invalidDocumentAlert;
@property (nonatomic, copy) NSString * _Nonnull textDescriptionInvalid;
@property (nonatomic, strong) UIColor * _Nullable doneButtonBackgroundDisableColor;
@property (nonatomic, strong) UIColor * _Nullable textDescriptionInvalidColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



enum JPEGQuality : NSInteger;

@interface UIImage (SWIFT_EXTENSION(BioSDK))
- (NSData * _Nullable)jpeg:(enum JPEGQuality)jpegQuality SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, JPEGQuality, open) {
  JPEGQualityLowest = 0,
  JPEGQualityLow = 1,
  JPEGQualityMedium = 2,
  JPEGQualityHigh = 3,
  JPEGQualityHighest = 4,
};




#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)
#ifndef BIOSDK_SWIFT_H
#define BIOSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BioSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSString;
@class NSNumber;
@class UIView;
@class UIColor;
enum PostionCamera : NSInteger;
@class FaceStep;
enum Language : NSInteger;

SWIFT_CLASS("_TtC6BioSDK13AdvanceOption")
@interface AdvanceOption : NSObject
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull help;
@property (nonatomic, copy) NSString * _Nonnull titleButtonRetake;
@property (nonatomic, copy) NSString * _Nonnull titleButtonNext;
@property (nonatomic) BOOL isShowTutorial;
@property (nonatomic, copy) NSString * _Nonnull logoNameImage;
@property (nonatomic) BOOL isShowLogo;
@property (nonatomic, copy) NSString * _Nonnull titleBtnHelp;
@property (nonatomic, strong) UIView * _Nullable contentPreviewView;
@property (nonatomic, strong) UIView * _Nullable tutorialView;
@property (nonatomic, copy) NSString * _Nonnull titleBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nonnull textColorBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nullable textColorBtnRetake;
@property (nonatomic, strong) UIColor * _Nullable textColorBtnNext;
@property (nonatomic, strong) UIColor * _Nullable bgColorBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nullable bgColor;
@property (nonatomic, strong) UIColor * _Nullable bgBtnRetakeColor;
@property (nonatomic, strong) UIColor * _Nullable bgNextColor;
@property (nonatomic) enum PostionCamera postionCamera;
@property (nonatomic, strong) UIColor * _Nullable progressBarColor;
@property (nonatomic, copy) NSString * _Nonnull imageTopLine;
@property (nonatomic, copy) NSString * _Nonnull imageSquareBottom;
@property (nonatomic, strong) UIColor * _Nullable colorStepNext;
@property (nonatomic) BOOL isShowArrowStep;
@property (nonatomic) BOOL isShowWaveGuilde;
@property (nonatomic) BOOL isAutoNext;
@property (nonatomic) NSInteger countdownTime;
@property (nonatomic, strong) UIColor * _Nullable titleColor;
@property (nonatomic, copy) NSString * _Nonnull iconBack;
@property (nonatomic, strong) UIColor * _Nullable textContentColor;
@property (nonatomic, strong) UIColor * _Nullable backgroundHelpButton;
@property (nonatomic, strong) UIColor * _Nullable textHelpButtonColor;
@property (nonatomic) BOOL isAnimatedDismiss;
@property (nonatomic) BOOL isShowPreviewTitle;
@property (nonatomic) BOOL isTakeMoreImage;
@property (nonatomic) BOOL isShowVersion;
@property (nonatomic, copy) NSDictionary<NSAttributedStringKey, id> * _Nullable titleAttributes;
@property (nonatomic, copy) NSDictionary<NSAttributedStringKey, id> * _Nullable titleButtonRetakeAttributes;
@property (nonatomic, copy) NSDictionary<NSAttributedStringKey, id> * _Nullable titleButtonNextAttributes;
@property (nonatomic, copy) NSDictionary<NSAttributedStringKey, id> * _Nullable titleBtnHelpAttributes;
@property (nonatomic, copy) NSDictionary<NSAttributedStringKey, id> * _Nullable titleBtnUnderstandAttributes;
@property (nonatomic, copy) NSDictionary<NSAttributedStringKey, id> * _Nullable textStepFaceAttributes;
@property (nonatomic, copy) NSArray<FaceStep *> * _Nonnull faceSteps;
@property (nonatomic) BOOL isVibrate;
@property (nonatomic) BOOL isMirrorFrontCamera;
@property (nonatomic) BOOL isStreamCapture;
@property (nonatomic) BOOL isRecord;
@property (nonatomic) NSInteger maxTimeRecord;
@property (nonatomic) enum Language tutorialLanguage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6BioSDK11BasicOption")
@interface BasicOption : NSObject
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull help;
@property (nonatomic, copy) NSString * _Nonnull titleButtonRetake;
@property (nonatomic, copy) NSString * _Nonnull titleButtonNext;
@property (nonatomic, copy) NSString * _Nonnull titleBtnHelp;
@property (nonatomic, copy) NSString * _Nonnull textContentPreview;
@property (nonatomic, strong) UIView * _Nullable tutorialView;
@property (nonatomic) BOOL isShowTutorial;
@property (nonatomic, copy) NSString * _Nonnull logoNameImage;
@property (nonatomic) BOOL isShowLogo;
@property (nonatomic, copy) NSString * _Nonnull titleBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nonnull textColorBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nullable textColorBtnRetake;
@property (nonatomic, strong) UIColor * _Nullable textColorBtnNext;
@property (nonatomic, strong) UIColor * _Nullable bgColorBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nullable bgColor;
@property (nonatomic, strong) UIColor * _Nullable bgBtnRetakeColor;
@property (nonatomic, strong) UIColor * _Nullable bgNextColor;
@property (nonatomic) enum PostionCamera postionCamera;
@property (nonatomic) BOOL isSwapCamera;
@property (nonatomic, copy) NSString * _Nonnull imageTopLine;
@property (nonatomic, copy) NSString * _Nonnull imageSquareBottom;
@property (nonatomic, strong) UIColor * _Nullable imageCircleColor;
@property (nonatomic) BOOL isAutoNext;
@property (nonatomic) NSInteger countdownTime;
@property (nonatomic, strong) UIColor * _Nullable titleColor;
@property (nonatomic, copy) NSString * _Nonnull iconBack;
@property (nonatomic, copy) NSString * _Nonnull iconSwapCamera;
@property (nonatomic, copy) NSString * _Nonnull iconTakePhoto;
@property (nonatomic, strong) UIColor * _Nullable textContentColor;
@property (nonatomic, strong) UIColor * _Nullable backgroundHelpButton;
@property (nonatomic, strong) UIColor * _Nullable textHelpButtonColor;
@property (nonatomic, strong) UIColor * _Nullable textContentPreviewColor;
@property (nonatomic) BOOL isAnimatedDismiss;
@property (nonatomic) BOOL isShowPreviewTitle;
@property (nonatomic) BOOL isShowVersion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@protocol CameraDelegate;
enum DocumentType : NSInteger;
@class OneSideOption;
@class TwoSideOption;
@class OvalOption;
@class UIViewController;

SWIFT_CLASS("_TtC6BioSDK6Camera")
@interface Camera : NSObject
@property (nonatomic, strong) id <CameraDelegate> _Nullable delegate;
@property (nonatomic) enum DocumentType documentType;
@property (nonatomic, strong) OneSideOption * _Nullable oneSideOption;
@property (nonatomic, strong) TwoSideOption * _Nullable twoSideOption;
@property (nonatomic, strong) BasicOption * _Nullable basicOption;
@property (nonatomic) enum Language language;
@property (nonatomic, strong) AdvanceOption * _Nonnull advanceOption;
@property (nonatomic, strong) OvalOption * _Nonnull ovalOption;
- (void)show:(UIViewController * _Nonnull)controller;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class DataModel;
@class UIImage;
enum FaceStepType : NSInteger;
@class ImageData;

SWIFT_PROTOCOL("_TtP6BioSDK14CameraDelegate_")
@protocol CameraDelegate
- (void)onResult:(DataModel * _Nonnull)data;
@optional
- (void)onStreamCapture:(UIImage * _Nonnull)image :(enum FaceStepType)type;
- (void)onStreamCaptureImageData:(ImageData * _Nonnull)image :(enum FaceStepType)type;
@required
- (void)onClose;
@optional
- (void)onError:(NSString * _Nonnull)message;
@end

@class NSURL;
@class NSData;

SWIFT_CLASS("_TtC6BioSDK9DataModel")
@interface DataModel : NSObject
@property (nonatomic, strong) UIImage * _Nullable image;
@property (nonatomic, strong) UIImage * _Nullable frontImage;
@property (nonatomic, strong) UIImage * _Nullable backImage;
@property (nonatomic, strong) UIImage * _Nullable farImage;
@property (nonatomic, strong) UIImage * _Nullable nearImage;
@property (nonatomic, strong) ImageData * _Nullable imageData;
@property (nonatomic, strong) ImageData * _Nullable frontImageData;
@property (nonatomic, strong) ImageData * _Nullable backImageData;
@property (nonatomic, strong) ImageData * _Nullable farImageData;
@property (nonatomic, strong) ImageData * _Nullable nearImageData;
@property (nonatomic) enum DocumentType documentType;
@property (nonatomic, copy) NSArray<UIImage *> * _Nonnull listPhoto;
@property (nonatomic, copy) NSArray<ImageData *> * _Nonnull listPhotoImageData;
@property (nonatomic) float topCropParam;
@property (nonatomic) float bottomCropParam;
@property (nonatomic, copy) NSArray<UIImage *> * _Nonnull listFaceSteps;
@property (nonatomic, copy) NSArray<ImageData *> * _Nonnull listFaceStepsImageData;
@property (nonatomic, copy) NSURL * _Nullable scanUrl;
@property (nonatomic, copy) NSData * _Nullable logData;
- (NSString * _Nonnull)getCropParam SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nonnull)cropImageWithImage:(UIImage * _Nonnull)image SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, DocumentType, open) {
  DocumentTypeOneside = 0,
  DocumentTypeTwoside = 1,
  DocumentTypeBasic = 3,
  DocumentTypeAdvanced = 4,
  DocumentTypeOval = 5,
};


SWIFT_CLASS("_TtC6BioSDK8FaceStep")
@interface FaceStep : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) enum FaceStepType type;
@property (nonatomic, strong) UIView * _Nullable viewGuide;
@property (nonatomic, copy) NSString * _Nonnull textGuide;
@property (nonatomic, copy) NSString * _Nonnull jsonArrowGuide;
@property (nonatomic, copy) NSString * _Nonnull jsonWaveGuide;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable dataJsonArrowGuide;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable dataJsonWaveGuide;
@end

typedef SWIFT_ENUM(NSInteger, FaceStepType, open) {
  FaceStepTypeLeft = 0,
  FaceStepTypeRight = 1,
  FaceStepTypeUp = 2,
  FaceStepTypeDown = 3,
  FaceStepTypeStraight = 4,
};


SWIFT_CLASS("_TtC6BioSDK9ImageData")
@interface ImageData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6BioSDK20InvalidDocumentAlert")
@interface InvalidDocumentAlert : NSObject
@property (nonatomic, copy) NSString * _Nonnull mesage;
@property (nonatomic, copy) NSString * _Nonnull buttonText;
@property (nonatomic, strong) UIColor * _Nullable messageColor;
@property (nonatomic, strong) UIColor * _Nullable buttonTextColor;
@property (nonatomic, strong) UIColor * _Nullable buttonColor;
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, Language, open) {
  LanguageVn = 0,
  LanguageEn = 1,
};

typedef SWIFT_ENUM(NSInteger, LivenessMode, open) {
  LivenessModeOnline = 0,
  LivenessModeOffline = 1,
};



SWIFT_CLASS("_TtC6BioSDK13OneSideOption")
@interface OneSideOption : NSObject
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull help;
@property (nonatomic, copy) NSString * _Nonnull titleButtonRetake;
@property (nonatomic, copy) NSString * _Nonnull titleButtonNext;
@property (nonatomic, copy) NSString * _Nonnull btnFinishTitle;
@property (nonatomic, copy) NSString * _Nonnull titleBtnHelp;
@property (nonatomic, copy) NSString * _Nonnull textContentPreview;
@property (nonatomic) BOOL isShowTutorial;
@property (nonatomic, copy) NSString * _Nonnull logoNameImage;
@property (nonatomic) BOOL isShowLogo;
@property (nonatomic, copy) NSString * _Nonnull titleBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nonnull textColorBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nullable textColorBtnRetake;
@property (nonatomic, strong) UIColor * _Nullable textColorBtnNext;
@property (nonatomic, strong) UIColor * _Nullable bgColorBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nullable bgColorPreview;
@property (nonatomic, strong) UIColor * _Nullable bgBtnRetakeColor;
@property (nonatomic, strong) UIColor * _Nullable bgNextColor;
@property (nonatomic, strong) UIView * _Nullable tutorialView;
@property (nonatomic) BOOL isAutoNext;
@property (nonatomic) NSInteger countdownTime;
@property (nonatomic, strong) UIColor * _Nullable titleColor;
@property (nonatomic, copy) NSString * _Nonnull iconBack;
@property (nonatomic, copy) NSString * _Nonnull textGuideImage;
@property (nonatomic, strong) UIColor * _Nullable backgroundHelpButton;
@property (nonatomic, strong) UIColor * _Nullable textHelpButtonColor;
@property (nonatomic, copy) NSString * _Nonnull iconTakePhoto;
@property (nonatomic, strong) UIColor * _Nullable textContentColor;
@property (nonatomic, strong) UIColor * _Nullable textContentPreviewColor;
@property (nonatomic, copy) NSString * _Nonnull jsonAnimationPreview;
@property (nonatomic, copy) NSString * _Nonnull imgBackgroundPreview;
@property (nonatomic, copy) NSString * _Nonnull imageTopViewCamera;
@property (nonatomic, copy) NSString * _Nonnull imageBottomViewCamera;
@property (nonatomic, copy) NSString * _Nonnull imageMarkFrameCamera;
@property (nonatomic, strong) UIColor * _Nullable textGuideImageColor;
@property (nonatomic) BOOL isAnimatedDismiss;
@property (nonatomic) BOOL isShowPreviewTitle;
@property (nonatomic) BOOL isShowVersion;
@property (nonatomic) BOOL isPreviewAnimation;
@property (nonatomic, strong) UIColor * _Nullable frameCornerColor;
@property (nonatomic, strong) UIColor * _Nullable backgroundCameraColor;
@property (nonatomic) BOOL isValidDocument;
@property (nonatomic, strong) InvalidDocumentAlert * _Nonnull invalidDocumentAlert;
@property (nonatomic, copy) NSString * _Nonnull textDescriptionInvalid;
@property (nonatomic, strong) UIColor * _Nullable doneButtonBackgroundDisableColor;
@property (nonatomic, strong) UIColor * _Nullable textDescriptionInvalidColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6BioSDK10OvalOption")
@interface OvalOption : NSObject
@property (nonatomic) BOOL isShowTutorial;
@property (nonatomic) BOOL isSkipTutorial;
@property (nonatomic) enum Language language;
@property (nonatomic, strong) UIView * _Nullable tutorialView;
@property (nonatomic, strong) UIImage * _Nullable bottomImage;
@property (nonatomic, strong) UIColor * _Nullable ovalCircleColor;
@property (nonatomic, strong) UIColor * _Nullable buttonTextColor;
@property (nonatomic, strong) UIColor * _Nullable textFeedbackColor;
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
@property (nonatomic, strong) UIColor * _Nullable bgColorBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nonnull textColorBtnUnderstand;
@property (nonatomic, copy) NSString * _Nonnull titleBtnUnderstand;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, PostionCamera, open) {
  PostionCameraBack = 0,
  PostionCameraFront = 1,
};

typedef SWIFT_ENUM(NSInteger, TutorialType, open) {
  TutorialTypeId = 0,
  TutorialTypeIdcard = 1,
  TutorialTypePassport = 2,
  TutorialTypeMilitary = 3,
  TutorialTypeBasic = 4,
  TutorialTypeAdvanced = 5,
};


SWIFT_CLASS("_TtC6BioSDK13TwoSideOption")
@interface TwoSideOption : NSObject
@property (nonatomic, copy) NSString * _Nonnull titleFont;
@property (nonatomic, copy) NSString * _Nonnull titleBack;
@property (nonatomic, copy) NSString * _Nonnull frontHelpPreview;
@property (nonatomic, copy) NSString * _Nonnull backHelpPreview;
@property (nonatomic, copy) NSString * _Nonnull frontHelp;
@property (nonatomic, copy) NSString * _Nonnull backHelp;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic) BOOL isShowTutorial;
@property (nonatomic, copy) NSString * _Nonnull logoNameImage;
@property (nonatomic) BOOL isShowLogo;
@property (nonatomic, copy) NSString * _Nonnull titleButtonRetake;
@property (nonatomic, copy) NSString * _Nonnull titleButtonNext;
@property (nonatomic, copy) NSString * _Nonnull btnFinishTitle;
@property (nonatomic, copy) NSString * _Nonnull titleBtnHelp;
@property (nonatomic, strong) UIView * _Nullable tutorialView;
@property (nonatomic, copy) NSString * _Nonnull titleBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nonnull textColorBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nullable textColorBtnRetake;
@property (nonatomic, strong) UIColor * _Nullable textColorBtnNext;
@property (nonatomic, strong) UIColor * _Nullable bgColorBtnUnderstand;
@property (nonatomic, strong) UIColor * _Nullable bgColorPreview;
@property (nonatomic, strong) UIColor * _Nullable bgBtnRetakeColor;
@property (nonatomic, strong) UIColor * _Nullable bgNextColor;
@property (nonatomic) BOOL isAutoNext;
@property (nonatomic) NSInteger countdownTime;
@property (nonatomic, strong) UIColor * _Nullable titleColor;
@property (nonatomic, copy) NSString * _Nonnull iconBack;
@property (nonatomic, strong) UIColor * _Nullable backgroundHelpButton;
@property (nonatomic, strong) UIColor * _Nullable textHelpButtonColor;
@property (nonatomic, copy) NSString * _Nonnull iconTakePhoto;
@property (nonatomic, strong) UIColor * _Nullable textContentColor;
@property (nonatomic, strong) UIColor * _Nullable textContentPreviewColor;
@property (nonatomic, copy) NSString * _Nonnull jsonAnimationPreview;
@property (nonatomic, copy) NSString * _Nonnull imgBackgroundPreview;
@property (nonatomic, copy) NSString * _Nonnull imageTopViewCamera;
@property (nonatomic, copy) NSString * _Nonnull imageBottomViewCamera;
@property (nonatomic, copy) NSString * _Nonnull imageMarkFrameCamera;
@property (nonatomic, strong) UIColor * _Nullable textGuideImageColor;
@property (nonatomic) BOOL isAnimatedDismiss;
@property (nonatomic) BOOL isShowPreviewTitle;
@property (nonatomic) BOOL isShowVersion;
@property (nonatomic) BOOL isPreviewAnimation;
@property (nonatomic, strong) UIColor * _Nullable frameCornerColor;
@property (nonatomic, strong) UIColor * _Nullable backgroundCameraColor;
@property (nonatomic) BOOL isValidDocument;
@property (nonatomic, strong) InvalidDocumentAlert * _Nonnull invalidDocumentAlert;
@property (nonatomic, copy) NSString * _Nonnull textDescriptionInvalid;
@property (nonatomic, strong) UIColor * _Nullable doneButtonBackgroundDisableColor;
@property (nonatomic, strong) UIColor * _Nullable textDescriptionInvalidColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



enum JPEGQuality : NSInteger;

@interface UIImage (SWIFT_EXTENSION(BioSDK))
- (NSData * _Nullable)jpeg:(enum JPEGQuality)jpegQuality SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, JPEGQuality, open) {
  JPEGQualityLowest = 0,
  JPEGQualityLow = 1,
  JPEGQualityMedium = 2,
  JPEGQualityHigh = 3,
  JPEGQualityHighest = 4,
};




#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
