name: vncitizens_common
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  digo_common:
    git: https://scm.devops.vnpt.vn/egov.pm4.digo/flutter_common.git
  iscs_common:
    git: https://scm.devops.vnpt.vn/egov.pm4.digo/flutter_iscs_common.git
  vncitizens_notification:
    path: ../vncitizens_notification
    # git:
    #   url: https://scm.devops.vnpt.vn/egov.ptpm.g038/flutter_vncitizens
    #   ref: v1.0.0
    #   path: packages/vncitizens_notification
  vncitizens_account:
    path: ../vncitizens_account
    # git:
    #   url: https://scm.devops.vnpt.vn/egov.ptpm.g038/flutter_vncitizens
    #   ref: v1.0.0
    #   path: packages/vncitizens_account
  get: ^4.6.1
  get_storage: ^2.0.3
  url_launcher: ^6.0.20
  intl: ^0.17.0
  geolocator: ^8.1.1
  weather: ^2.0.1
  hive: ^2.0.5
  carousel_slider: ^4.0.0
  package_info_plus: ^1.3.0
  internet_connection_checker: ^0.0.1+3
  google_fonts: ^2.3.1
  photo_view: ^0.13.0
  timezone: ^0.8.0
  badges: ^2.0.2
  flutter_spinkit: ^5.1.0
  jwt_decode: ^0.3.1
  email_validator: ^2.0.1
  path_provider: ^2.0.9
  http: ^0.13.4
  dio: ^4.0.4
  image_picker: ^0.8.4+11
  image_cropper: ^1.5.0
  minio: ^3.5.0
  drishya_picker: ^1.0.3
  objectid: ^2.1.0
  path: ^1.8.0
  permission_handler: ^8.3.0
  flutter_share: ^2.0.0
  qr_code_scanner: ^0.6.1
  flutter_sms: ^2.3.2
  wifi_iot: ^0.3.15
  firebase_core: ^1.10.6
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.5.3+1
  platform_device_id: ^1.0.1
  file_picker: ^4.6.0
  #  dotted_border: ^2.0.0+2
  video_player: ^2.4.2
  video_thumbnail: ^0.5.0
  expandable: ^5.0.1
  flutter_html: ^2.2.1
  flutter_map: ^0.14.0
  flutter_map_marker_popup: ^2.1.2
  geocoding: ^2.0.4
  flutter_widget_from_html: ^0.8.5
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: 0.23.0+1
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/vncitizens_common/assets/images/internet.png
    - packages/vncitizens_common/assets/images/success.png
    - packages/vncitizens_common/assets/images/warning.png
    - packages/vncitizens_common/assets/images/empty_data.png
    - packages/vncitizens_common/assets/images/error.png
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
