name: vncitizens_account
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pretty_json: ^2.0.0
  jwt_decoder: ^2.0.1
  path_provider: ^2.0.8
  vncitizens_common:
    git:
      url: https://scm.devops.vnpt.vn/egov.ptpm.g038/flutter_vncitizens
      ref: v1.0.0
      path: packages/vncitizens_common
  vncitizens_petition:
    git:
      url: https://scm.devops.vnpt.vn/egov.ptpm.g038/flutter_vncitizens
      ref: v1.0.0
      path: packages/vncitizens_petition
  vncitizens_setting:
    git:
      url: https://scm.devops.vnpt.vn/egov.ptpm.g038/flutter_vncitizens
      ref: v1.0.0
      path: packages/vncitizens_setting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/vncitizens_account/assets/images/success.png
    - packages/vncitizens_account/assets/images/error.png
    - packages/vncitizens_account/assets/images/warning.png
    - packages/vncitizens_account/assets/images/cmnd.jpg
    - packages/vncitizens_account/assets/images/cccd.jpg
    - packages/vncitizens_account/assets/images/passport.jpg
    - packages/vncitizens_account/assets/images/cccd_1.jpg
    - packages/vncitizens_account/assets/images/cmnd_1.jpg
    - packages/vncitizens_account/assets/images/passport_1.jpg
    - packages/vncitizens_account/assets/images/avatar_login_1.jpg
    - packages/vncitizens_account/assets/images/avatar_login.png
    - packages/vncitizens_account/assets/images/face_scan.jpg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
